<?php

/**
 * Class InputsVue
 * This class was generated by Unicorn as view
 * @author lio
 */

class InputsVue extends IVue {
    public function __toString() {
        $this->content = '
		    Inputs view
        ';

        return $this->generate();
    }
}

?>
