<?php

/**
 * Class LoginsVue
 * This class was generated by Unicorn as view
 * @author lio
 */

class LoginsVue extends IVue {
    public function __toString() {
        $this->content = '
		    Logins view
        ';

        return $this->generate();
    }
}

?>
