<?php

/**
 * Class PictureManagerVue
 * This class was generated by Unicorn as view
 * @author gchanteloube
 */

class PictureManagerVue extends IVue {
    public function __toString() {
        $d = $this->getMdonnees();

        $text = '
        
        <!--
            <div class="home-wrapper">
               <img src="http://localhost/Ui-features/Pictures/1.jpg">
            </div>
        -->
        
        <div class="picture-container">
        
        </div>
        
        
        ';


        $js = '
            var home = new Home();
            home.init();
        ';
        $text .= Utils::insertJavaScriptCode($js);

        return $text;
    }

}

?>
