<?php

/**
 * Class ButtonsVue
 * This class was generated by Unicorn as view
 * @author lio
 */

class ButtonsVue extends IVue {
    public function __toString() {
        $this->content = '
		   
            <div class="ui-wrapper">
                <div class="btn-wrapper">
                    <h1> Button sets </h1>
                    <div class="xs-line"></div>
                    <h2> Default Button sets </h2>
                    <div class="btn-dft-wrapper">
                        <button class="dft-btn light-blue-bg"> Hello! </button>
                        <button class="dft-btn lagoon-bg rad"> Hello! </button>
                        <button class="dft-btn sea-blue-bg sh"> Hello! </button>
                        <button class="dft-btn dark-blue-bg rad sh"> Hello! </button>
                        <button class="dft-btn yellow-sun-bg rad-h"> Hello! </button>
                        <button class="dft-btn sunset-bg no-bd"> Hello! </button>
                        <button class="dft-btn bloody-bg"> Hello! </button>
                        <button class="dft-btn industrial-bg"> Hello! </button>
                    </div>
                    <h2> Default Button sets - L sized </h2>
                    <div class="btn-dft-wrapper">
                        <button class="dft-btn l-size light-blue-bg"> Hello! </button>
                        <button class="dft-btn l-size lagoon-bg rad"> Hello! </button>
                        <button class="dft-btn l-size sea-blue-bg sh"> Hello! </button>
                        <button class="dft-btn l-size dark-blue-bg rad sh"> Hello! </button>
                        <button class="dft-btn l-size yellow-sun-bg rad-h"> Hello! </button>
                        <button class="dft-btn l-size sunset-bg no-bd"> Hello! </button>
                        <button class="dft-btn l-size bloody-bg"> Hello! </button>
                        <button class="dft-btn l-size industrial-bg"> Hello! </button>
                    </div>
                    <h2> Default Button sets - XL sized </h2>
                    <div class="btn-dft-wrapper">
                        <button class="dft-btn xl-size light-blue-bg"> Hello! </button>
                        <button class="dft-btn xl-size lagoon-bg rad"> Hello! </button>
                        <button class="dft-btn xl-size sea-blue-bg sh"> Hello! </button>
                        <button class="dft-btn xl-size dark-blue-bg rad sh"> Hello! </button>
                        <button class="dft-btn xl-size yellow-sun-bg rad-h"> Hello! </button>
                        <button class="dft-btn xl-size sunset-bg no-bd"> Hello! </button>
                        <button class="dft-btn xl-size bloody-bg"> Hello! </button>
                        <button class="dft-btn xl-size industrial-bg"> Hello! </button>
                    </div>
                    <h2> Default Social Button sets </h2>
                    <div class="btn-dft-wrapper">
                        <button class="dft-btn xl-size light-blue-bg"> 
                            <i class="fa fa-facebook" aria-hidden="true"></i> Share
                        </button>
                        <button class="dft-btn xl-size lagoon-bg rad"> 
                            <i class="fa fa-twitter" aria-hidden="true"></i> Share
                        </button>
                        <button class="dft-btn xl-size sea-blue-bg sh"> 
                            <i class="fa fa-google-plus" aria-hidden="true"></i> Share
                        </button>
                        <button class="dft-btn xl-size dark-blue-bg rad sh"> 
                            <i class="fa fa-pinterest-p" aria-hidden="true"></i> Share
                        </button>
                        <button class="dft-btn xl-size yellow-sun-bg rad-h"> 
                            <i class="fa fa-tumblr" aria-hidden="true"></i> Share
                        </button>
                        <button class="dft-btn xl-size sunset-bg no-bd"> 
                        <i class="fa fa-500px" aria-hidden="true"></i> Share 
                        </button>
                        <button class="dft-btn xl-size bloody-bg"> 
                            <i class="fa fa-vine" aria-hidden="true"></i> Share
                        </button>
                    </div>
                    <h2> Twitter like button </h2>
                    <div class="btn-dft-wrapper">
                        <button class="dft-btn sq-btn bloody-rad"> 
                            <i class="fa fa-envelope-o" aria-hidden="true"></i>
                        </button>
                        <button class="dft-btn sq-btn blue-lagoon-rad"> 
                            <i class="fa fa-twitter" aria-hidden="true"></i>
                        </button>
                        <button class="dft-btn sq-btn sunset-rad"> 
                            <i class="fa fa-envelope-o" aria-hidden="true"></i>
                        </button>
                        <button class="dft-btn sq-btn grey-rad"> 
                            <i class="fa fa-twitter" aria-hidden="true"></i>
                        </button>
                    </div>
                </div>
            </div>
        ';

        return $this->generate();
    }
}

?>
